import { useState } from 'react';
import { 
    Search, Filter, MapPin, Globe, TrendingUp, Mail, 
    MessageSquare, PhoneCall, Zap, Star, AlertCircle, CheckCircle2,
    BarChart3, Activity, Users, Target, Play, Download
} from 'lucide-react';
import { useToast } from '../../context/ToastContext';
import { useData } from '../../context/DataContext';
import { AiService } from '../../services/AiService';
import { EmailService } from '../../services/EmailService';

export default function AiSalesPlatform() {
    const { showToast } = useToast();
    const { allLeads, setAllLeads } = useData();
    
    const [activeTab, setActiveTab] = useState('discovery');
    const [isSearching, setIsSearching] = useState(false);
    const [searchPrompt, setSearchPrompt] = useState('');
    const [discoveredData, setDiscoveredData] = useState([]);

    // AI Email Generation State
    const [selectedOutreachLeadId, setSelectedOutreachLeadId] = useState('');
    const [isGeneratingEmail, setIsGeneratingEmail] = useState(false);
    const [generatedEmail, setGeneratedEmail] = useState('');
    const [receiverEmail, setReceiverEmail] = useState('');

    // Intelligence State
    const [selectedIntelligenceLeadId, setSelectedIntelligenceLeadId] = useState('');
    const [isGatheringIntel, setIsGatheringIntel] = useState(false);
    const [intelData, setIntelData] = useState(null);

    const handleSearchClick = async () => {
        if (!searchPrompt.trim()) return;
        setIsSearching(true);
        showToast('Initiating NVIDIA AI Search...');
        
        try {
            const results = await AiService.discoverLeads(searchPrompt);
            setDiscoveredData(results);
            showToast(`Search complete. Found ${results.length} highly qualified prospects.`);
        } catch (error) {
            console.error("AI Search Error:", error);
            showToast('Error communicating with AI Service.');
        } finally {
            setIsSearching(false);
        }
    };

    const handleAddToCRM = (prospect) => {
        const newLead = {
            id: `L${String(allLeads.length + 1).padStart(3, '0')}`,
            company: prospect.company,
            contact: 'TBD', 
            phone: '',
            email: 'contact@' + prospect.company.toLowerCase().replace(/[^a-z0-9]/g, '') + '.com',
            stage: 'New Lead',
            product: 'Determining needs...',
            qty: 0,
            value: prospect.matchScore > 90 ? 500000 : 150000,
            source: 'AI Lead Discovery',
            assignedTo: 'AI Agent',
            lastActivity: new Date().toISOString().split('T')[0],
            notes: `Auto-generated by AI Discovery.\nMatch Score: ${prospect.matchScore}%\nIndustry: ${prospect.industry}\nIntent: ${prospect.intent}`
        };
        
        setAllLeads([...allLeads, newLead]);
        showToast(`✅ ${prospect.company} added to CRM Pipeline!`);
        
        setDiscoveredData(prev => prev.filter(p => p.id !== prospect.id));
    };

    const handleGenerateEmail = async () => {
        if (!selectedOutreachLeadId) {
            showToast('Please select a lead from your CRM first.');
            return;
        }

        const lead = allLeads.find(l => l.id === selectedOutreachLeadId);
        if (!lead) return;

        setIsGeneratingEmail(true);
        setGeneratedEmail('');
        
        // Auto-fill receiver email from lead
        if (lead.email) {
            setReceiverEmail(lead.email);
        }

        try {
            showToast('Drafting hyper-personalized email...');
            const emailContent = await AiService.generateEmail(lead);
            setGeneratedEmail(emailContent);
            showToast('✅ Hyper-personalized email generated successfully!');
        } catch (error) {
            console.error("Email Gen Error:", error);
            showToast('Failed to generate email.');
        } finally {
            setIsGeneratingEmail(false);
        }
    };

    const handleSendEmail = async () => {
        if (!generatedEmail) return;
        if (!receiverEmail) {
            showToast('Please enter a receiver email address.');
            return;
        }

        try {
            showToast('Sending email via SMTP...');
            const subjectLine = generatedEmail.split('\n')[0].replace('Subject:', '').trim() || 'Introduction';
            const bodyHtml = `<p>${generatedEmail.replace(/\n/g, '<br/>')}</p>`;
            await EmailService.sendEmail(receiverEmail, subjectLine, bodyHtml);
            showToast('✅ Email sent successfully!');
        } catch (error) {
            showToast(error.message || 'Failed to send email. Check SMTP settings.');
        }
    };

    const handleDownloadEmail = () => {
        const element = document.createElement("a");
        const file = new Blob([generatedEmail], {type: 'text/plain'});
        element.href = URL.createObjectURL(file);
        element.download = `email_draft_${selectedOutreachLeadId}.txt`;
        document.body.appendChild(element); 
        element.click();
        document.body.removeChild(element);
        showToast('Draft downloaded.');
    };


    const handleGatherIntelligence = async () => {
        if (!selectedIntelligenceLeadId) {
            showToast('Please select a lead to analyze.'); 
            return;
        }
        const lead = allLeads.find(l => l.id === selectedIntelligenceLeadId);
        setIsGatheringIntel(true);
        setIntelData(null);
        showToast(`Scraping Google & News for ${lead.company}...`);
        
        try {
            const data = await AiService.gatherIntelligence(lead.company);
            setIntelData(data);
            showToast('✅ Intelligence compiled successfully.');
        } catch(e) {
            console.error("Intel Error:", e);
            showToast('Failed to compile intelligence.');
        } finally {
            setIsGatheringIntel(false);
        }
    };

    return (
        <div className="page-content" style={{ padding: '0 0 24px 0', overflowX: 'hidden' }}>
            {/* Hero Header */}
            <div style={{
                background: 'linear-gradient(180deg, rgba(99, 102, 241, 0.1) 0%, rgba(10, 14, 26, 0) 100%)',
                padding: '32px 32px 0 32px',
                borderBottom: '1px solid var(--border-color)',
                marginBottom: '24px'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px' }}>
                    <div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                            <div style={{ background: 'var(--gradient-primary)', padding: '8px', borderRadius: '8px', color: 'white', display: 'flex' }}>
                                <Zap size={20} />
                            </div>
                            <h1 style={{ fontSize: '24px', fontWeight: 800, margin: 0 }}>AI Sales Platform</h1>
                        </div>
                        <p style={{ color: 'var(--text-muted)', fontSize: '14px', maxWidth: '600px' }}>
                            End-to-end autonomous lead generation, qualification, and smart outreach. 
                        </p>
                    </div>
                </div>

                {/* Tabs */}
                <div style={{ display: 'flex', gap: '2px', borderBottom: '1px solid var(--border-color)', paddingTop: '8px' }}>
                    {[
                        { id: 'discovery', icon: Search, label: 'Lead Discovery' },
                        { id: 'intelligence', icon: Activity, label: 'Lead Intelligence' },
                        { id: 'outreach', icon: Mail, label: 'Smart Outreach' },
                        { id: 'crm', icon: Users, label: 'CRM Pipeline' },
                        { id: 'analytics', icon: BarChart3, label: 'Analytics' }
                    ].map(t => (
                        <button
                            key={t.id}
                            onClick={() => setActiveTab(t.id)}
                            style={{
                                display: 'flex', alignItems: 'center', gap: '8px',
                                padding: '12px 24px', background: 'none', border: 'none',
                                color: activeTab === t.id ? 'var(--accent-blue-light)' : 'var(--text-muted)',
                                borderBottom: activeTab === t.id ? '2px solid var(--accent-blue-light)' : '2px solid transparent',
                                fontWeight: activeTab === t.id ? 700 : 500,
                                fontSize: '13px', cursor: 'pointer',
                                transition: 'all 0.2s',
                                marginBottom: '-1px'
                            }}
                        >
                            <t.icon size={16} />
                            {t.label}
                        </button>
                    ))}
                </div>
            </div>

            <div style={{ padding: '0 32px' }}>
                {activeTab === 'discovery' && (
                    <div style={{ animation: 'fadeIn 0.4s ease' }}>
                        {/* Search Bar Block */}
                        <div className="card-glass" style={{ marginBottom: '24px', background: 'rgba(99, 102, 241, 0.03)', border: '1px solid rgba(99, 102, 241, 0.2)' }}>
                            <div style={{ display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
                                <div style={{ flex: 1 }}>
                                    <label style={{ display: 'block', fontSize: '12px', color: 'var(--accent-blue-light)', fontWeight: 700, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '1px' }}>
                                        AI Search Prompt
                                    </label>
                                    <div style={{ position: 'relative' }}>
                                        <div style={{ position: 'absolute', top: '14px', left: '16px', color: 'var(--accent-blue)' }}>
                                            <Search size={18} />
                                        </div>
                                        <input 
                                            value={searchPrompt}
                                            onChange={(e) => setSearchPrompt(e.target.value)}
                                            style={{
                                                width: '100%', background: 'var(--bg-primary)', border: '1px solid var(--border-color)',
                                                borderRadius: '8px', padding: '14px 16px 14px 44px', color: 'white', fontSize: '15px',
                                                boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.2)', transition: 'border 0.2s', outline: 'none'
                                            }}
                                            onFocus={(e) => e.target.style.borderColor = 'var(--accent-blue)'}
                                            onBlur={(e) => e.target.style.borderColor = 'var(--border-color)'}
                                        />
                                    </div>
                                </div>
                                <div style={{ paddingTop: '24px' }}>
                                    <button 
                                        className="btn btn-primary" style={{ padding: '14px 24px', fontSize: '14px' }}
                                        onClick={handleSearchClick}
                                        disabled={isSearching}
                                    >
                                        {isSearching ? <Activity className="spin" size={18} /> : <Zap size={18} />}
                                        {isSearching ? 'Scanning Sources...' : 'Discover Leads'}
                                    </button>
                                </div>
                            </div>
                            

                        </div>

                        {/* Results Table */}
                        <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                            <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <div>
                                    <h3 style={{ fontSize: '15px', fontWeight: 600 }}>Discovered Prospects</h3>
                                    <p style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Sourced from LinkedIn, TradeIndia, and Google Maps API.</p>
                                </div>
                                <button className="btn btn-secondary btn-sm"><Filter size={14}/> Filter Results</button>
                            </div>
                            <div style={{ overflowX: 'auto' }}>
                                <table className="data-table">
                                    <thead>
                                        <tr>
                                            <th>Company</th>
                                            <th>Location</th>
                                            <th>Industry</th>
                                            <th>AI Match Score</th>
                                            <th>Buying Intent</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {discoveredData.length === 0 ? (
                                            <tr>
                                                <td colSpan="6" style={{ textAlign: 'center', padding: '32px 0', color: 'var(--text-muted)' }}>
                                                    All discovered leads added. Run a new search to find more.
                                                </td>
                                            </tr>
                                        ) : (
                                            discoveredData.map(lead => (
                                                <tr key={lead.id}>
                                                    <td>
                                                        <div style={{ fontWeight: 600 }}>{lead.company}</div>
                                                        <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>Size: {lead.size}</div>
                                                    </td>
                                                    <td>
                                                        <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><MapPin size={12}/> {lead.location}</div>
                                                    </td>
                                                    <td>{lead.industry}</td>
                                                    <td>
                                                        <div className="badge" style={{ background: lead.matchScore > 90 ? 'rgba(16,185,129,0.15)' : 'rgba(245,158,11,0.15)', color: lead.matchScore > 90 ? 'var(--accent-green)' : 'var(--accent-orange)' }}>
                                                            <Star size={10} style={{ fill: 'currentColor' }}/> {lead.matchScore}% Match
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div style={{ fontSize: '12px', color: lead.intent.includes('High') ? 'var(--accent-red)' : 'var(--text-secondary)' }}>
                                                            {lead.intent.includes('High') ? '🔥 ' : lead.intent.includes('Medium') ? '⚠️ ' : '❄️ '}{lead.intent}
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <button className="btn btn-secondary btn-sm" onClick={() => handleAddToCRM(lead)}>
                                                            <Target size={12} /> Add to CRM
                                                        </button>
                                                    </td>
                                                </tr>
                                            ))
                                        )}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'intelligence' && (
                    <div style={{ animation: 'fadeIn 0.4s ease' }}>
                        <div className="card" style={{ marginBottom: '24px' }}>
                            <div className="card-header">
                                <div>
                                    <h3 className="card-title">Select Lead for Intelligence Scraping</h3>
                                    <p className="card-subtitle">Scrapes Google & News using Serper + NVIDIA</p>
                                </div>
                                <Activity size={20} color="var(--accent-blue)"/>
                            </div>
                            <div className="flex gap-4">
                                <select 
                                    className="form-select flex-1"
                                    value={selectedIntelligenceLeadId}
                                    onChange={(e) => setSelectedIntelligenceLeadId(e.target.value)}
                                >
                                    <option value="" disabled>Select a lead from your pipeline...</option>
                                    {allLeads.map(lead => (
                                        <option key={lead.id} value={lead.id}>{lead.company}</option>
                                    ))}
                                </select>
                                <button 
                                    className="btn btn-primary" 
                                    onClick={handleGatherIntelligence}
                                    disabled={isGatheringIntel || !selectedIntelligenceLeadId}
                                    style={{ padding: '0 32px' }}
                                >
                                    {isGatheringIntel ? <Activity className="spin" size={14} /> : <Search size={14}/>} 
                                    {isGatheringIntel ? 'Gathering...' : 'Gather Intel'}
                                </button>
                            </div>
                        </div>

                        {intelData && (
                            <div className="grid-2">
                                <div className="card">
                                    <div className="card-header">
                                        <div>
                                            <h3 className="card-title">Website Analysis Tools</h3>
                                            <p className="card-subtitle">AI parsing of target prospect</p>
                                        </div>
                                        <Globe className="text-blue" size={20} color="var(--accent-blue)"/>
                                    </div>
                                    <div style={{ background: 'var(--bg-secondary)', padding: '16px', borderRadius: '8px', border: '1px solid var(--border-color)', marginBottom: '16px' }}>
                                        <div style={{ fontSize: '13px', lineHeight: '1.6', color: 'var(--text-secondary)' }}>
                                            <strong style={{ color: 'white' }}>AI Conclusion:</strong> {intelData.websiteAnalysis}
                                        </div>
                                    </div>
                                </div>
                                <div className="card">
                                    <div className="card-header">
                                        <div>
                                            <h3 className="card-title">Job Postings & News Signals</h3>
                                            <p className="card-subtitle">Indications of demand expansion</p>
                                        </div>
                                        <TrendingUp className="text-green" size={20} color="var(--accent-green)"/>
                                    </div>
                                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                        <li style={{ display: 'flex', gap: '12px' }}>
                                            <div style={{ padding: '6px', background: 'rgba(99,102,241,0.1)', color: 'var(--accent-blue)', borderRadius: '6px' }}><Play size={16}/></div>
                                            <div>
                                                <div style={{ fontSize: '13px', fontWeight: 600 }}>Recent News / Signals</div>
                                                <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>{intelData.newsSignals}</div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div className="card" style={{ gridColumn: '1 / -1' }}>
                                    <div className="card-header">
                                        <div>
                                            <h3 className="card-title">Competitor & Supplier Gap Analysis</h3>
                                            <p className="card-subtitle">Identify weak suppliers used by leads in your CRM</p>
                                        </div>
                                        <AlertCircle size={20} color="orange"/>
                                    </div>
                                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center', background: 'var(--bg-secondary)', padding: '20px', borderRadius: '12px' }}>
                                        <div style={{ flex: 1 }}>
                                            <h4 style={{ fontSize: '14px', marginBottom: '8px' }}>Actionable Pitch Strategy:</h4>
                                            <p style={{ fontSize: '13px', color: 'var(--text-muted)', lineHeight: '1.5' }}>
                                                <strong>{intelData.competitorGap}</strong>
                                            </p>
                                        </div>
                                        <button className="btn btn-primary" onClick={() => { setActiveTab('outreach'); setSelectedOutreachLeadId(selectedIntelligenceLeadId); }}>Generate Strike Pitch</button>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                )}


                {activeTab === 'outreach' && (
                    <div style={{ animation: 'fadeIn 0.4s ease' }} className="grid-2">
                        {/* Email Generator */}
                        <div className="card">
                            <div className="card-header">
                                <div>
                                    <h3 className="card-title">Smart Email Generation</h3>
                                    <p className="card-subtitle">Pick a CRM Lead & Contextually generate outreach</p>
                                </div>
                                <Mail size={20} color="var(--accent-blue-light)"/>
                            </div>
                            <div className="form-group">
                                <label className="form-label">Target Prospect from CRM</label>
                                <select 
                                    className="form-select"
                                    value={selectedOutreachLeadId}
                                    onChange={(e) => setSelectedOutreachLeadId(e.target.value)}
                                >
                                    <option value="" disabled>Select a lead from your pipeline...</option>
                                    {allLeads.map(lead => (
                                        <option key={lead.id} value={lead.id}>
                                            {lead.company} ({lead.stage})
                                        </option>
                                    ))}
                                </select>
                            </div>
                            
                            <button 
                                className="btn btn-primary" 
                                style={{ width: '100%', justifyContent: 'center', marginBottom: '20px' }}
                                onClick={handleGenerateEmail}
                                disabled={isGeneratingEmail || !selectedOutreachLeadId}
                            >
                                {isGeneratingEmail ? <Activity className="spin" size={14} /> : <Zap size={14}/>} 
                                {isGeneratingEmail ? 'AI is drafting...' : 'Generate Hyper-Personalized Email'}
                            </button>
                            
                                {generatedEmail && (
                                    <div style={{ background: 'var(--bg-primary)', padding: '16px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)' }}>
                                        <div style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: '1.6', whiteSpace: 'pre-wrap' }}>
                                            {generatedEmail}
                                        </div>
                                        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '16px' }}>
                                            <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                                                <input 
                                                    type="email" 
                                                    className="form-input" 
                                                    style={{ flex: 1 }}
                                                    placeholder="Receiver Email (e.g. buyer@domain.com)"
                                                    value={receiverEmail}
                                                    onChange={e => setReceiverEmail(e.target.value)}
                                                />
                                                <button className="btn btn-success" onClick={handleSendEmail}>
                                                    <Mail size={16}/> Send Now
                                                </button>
                                                <button className="btn btn-secondary" onClick={handleDownloadEmail}>
                                                    <Download size={16}/> Download
                                                </button>
                                            </div>
                                            <button className="btn btn-secondary" onClick={() => showToast('WhatsApp outreach queued!')}>
                                                <MessageSquare size={16}/> Send WhatsApp
                                            </button>
                                        </div>
                                    </div>
                                )}
                        </div>

                        {/* Call Script Generator */}
                        <div className="card">
                            <div className="card-header">
                                <div>
                                    <h3 className="card-title">AI Audio/Call Script</h3>
                                    <p className="card-subtitle">Objection handling and pitch scripts</p>
                                </div>
                                <PhoneCall size={20} color="var(--accent-green)"/>
                            </div>
                            
                            <div style={{ background: 'var(--bg-secondary)', padding: '16px', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
                                <div className="badge green" style={{ marginBottom: '12px' }}>Opening Pitch</div>
                                <p style={{ fontSize: '13px', lineHeight: '1.5', marginBottom: '16px' }}>
                                    "Hi {allLeads.find(l => l.id === selectedOutreachLeadId)?.contact || '[Name]'}, I'm calling because we help OEMs eliminate production delays caused by spring suppliers. I know you're ramping up production—are you open to a backup supplier to ensure zero downtime?"
                                </p>
                                
                                <div className="badge purple" style={{ marginBottom: '12px' }}>Objection: "We already have a supplier"</div>
                                <p style={{ fontSize: '13px', lineHeight: '1.5', color: 'var(--text-secondary)' }}>
                                    "I completely understand. Most of our best clients started by just keeping us as a secondary vendor for emergencies or complex small batches. No commitment required. Can I send over our technical tolerance specs?"
                                </p>
                            </div>

                            <button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center', marginTop: '20px', background: 'linear-gradient(135deg, #ec4899, #8b5cf6)' }} onClick={() => showToast('Voice AI Dialing initialized...')}>
                                <Target size={14}/> Launch Voice AI Assistant
                            </button>
                            <p style={{ fontSize: '11px', color: 'var(--text-muted)', textAlign: 'center', marginTop: '8px' }}>Let our AI voice agent perform the cold call and qualify them.</p>
                        </div>
                    </div>
                )}
                
                {activeTab === 'crm' && (
                    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '400px', flexDirection: 'column', gap: '16px' }}>
                        <Users size={48} color="var(--text-muted)" />
                        <h3 style={{ fontSize: '18px' }}>CRM Pipeline Ready</h3>
                        <p style={{ color: 'var(--text-muted)', fontSize: '14px', maxWidth: '400px', textAlign: 'center' }}>
                            Your AI leads have been successfully synced to the database. <br/><br/>
                            Verify them by navigating to the "CRM Pipeline" menu externally, where you can move them across your Kanban flow.
                        </p>
                    </div>
                )}
                {activeTab === 'analytics' && (
                    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '400px', flexDirection: 'column', gap: '16px' }}>
                        <BarChart3 size={48} color="var(--text-muted)" />
                        <h3 style={{ fontSize: '18px' }}>Intelligence Analytics</h3>
                        <p style={{ color: 'var(--text-muted)', fontSize: '14px', maxWidth: '400px', textAlign: 'center' }}>Track revenue per AI lead source, test open rates across campaigns, and see voice agent success metrics.</p>
                    </div>
                )}
            </div>

            {/* Floating CSS overrides for animations specific to this page */}
            <style dangerouslySetInnerHTML={{__html: `
                @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
                @keyframes spin { 100% { transform: rotate(360deg); } }
                .spin { animation: spin 1s linear infinite; }
            `}} />
        </div>
    );
}
